### ISSUE TITLE
Closure Compiler optimized libv86.js breaks test error reporting.

### ISSUE THREAD

**Issue by MailYouLater** [copy/v86#385]
When one of the tests run by `tests/full/run.js` fails, it reports `ReferenceError: window is not defined` instead of giving a more appropriate error message.  When it does so, it points to the part of `libv86.js` associated with these lines: https://github.com/copy/v86/blob/f6ae3ea58aee15f2a9be71f2847738367ef31747/src/browser/mouse.js#L37-L44

If you analyze the code in the repository, this error seems to make no sense, since the only place that I could find that calls the function these lines are in verifies that `window` is defined first, however... GitHub Actions uses the `libv86.js` file which has been processed by Closure Compiler, and apparently in its attempts to optimize things, it restructures some of the code in a way that it ends up executing these lines when it shouldn't.

Since this doesn't technically seem to be an issue with the code in this repository, but rather an issue with how the closure compiler is rewriting it, and since I'm currently having other issues which prevent me from testing how Closure Compiler might handle any changes I would make, I'm unsure what the correct method of fixing this is, but for now what I've done locally is to manually edit my libv86.js file (downloaded from the releases page) to add `if (typof window!=="undefined"){…}` around the code from those lines.

If possible, please fix this.

---
### For reference, this is the exact change I made locally:
```diff
@@ -1171 +1171 @@
-function(a){this.enabled=a},this);this.destroy=function(){window.removeEventListener("touchstart",d,!1);window.removeEventListener("touchend",e,!1);window.removeEventListener("touchmove",f,!1);window.removeEventListener("mousemove",f,!1);window.removeEventListener("mousedown",g,!1);window.removeEventListener("mouseup",k,!1);window.removeEventListener("DOMMouseScroll",m,!1);window.removeEventListener("mousewheel",m,!1)};this.init=function(){"undefined"!==typeof window&&(this.destroy(),window.addEventListener("touchstart",
+function(a){this.enabled=a},this);this.destroy=function(){if(typeof window!=="undefined"){window.removeEventListener("touchstart",d,!1);window.removeEventListener("touchend",e,!1);window.removeEventListener("touchmove",f,!1);window.removeEventListener("mousemove",f,!1);window.removeEventListener("mousedown",g,!1);window.removeEventListener("mouseup",k,!1);window.removeEventListener("DOMMouseScroll",m,!1);window.removeEventListener("mousewheel",m,!1)}};this.init=function(){"undefined"!==typeof window&&(this.destroy(),window.addEventListener("touchstart",
```

### Before:
```
Starting test: Linux with Bochs BIOS
C:\v86\build\libv86.js:1171
function(a){this.enabled=a},this);this.destroy=function(){window.removeEventListener("touchstart",d,!1);window.removeEventListener("touchend",e,!1);window.removeEventListener("touchmove",f,!1);window.removeEventListener("mousemove",f,!1);window.removeEventListener("mousedown",g,!1);window.removeEventListener("mouseup",k,!1);window.removeEventListener("DOMMouseScroll",m,!1);window.removeEventListener("mousewheel",m,!1)};this.init=function(){"undefined"!==typeof window&&(this.destroy(),window.addEventListener("touchstart",
                                                          ^

ReferenceError: window is not defined
    at MouseAdapter.destroy (C:\v86\build\libv86.js:1171:59)
    at V86Starter.destroy (C:\v86\build\libv86.js:1233:219)
    at Timeout.check_test_done (C:\v86\tests\full\run.js:366:22)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
```
### After:
```
Starting test: Linux with Bochs BIOS
+==================================== SCREEN ====================================+
|Plex86/Bochs VGABios (PCI) current-cvs 08 Jul 2014                              |
|This VGA/VBE Bios is released under the GNU LGPL                                |
|                                                                                |
|Please visit :                                                                  |
| . http://bochs.sourceforge.net                                                 |
| . http://www.nongnu.org/vgabios                                                |
|                                                                                |
|Bochs VBE Display Adapter enabled                                               |
|                                                                                |
|Bochs BIOS - build: 02/16/17                                                    |
|$Revision: 13073 $ $Date: 2017-02-16 22:43:52 +0100 (Do, 16. Feb 2017) $        |
|Options: apmbios pcibios pnpbios eltorito                                       |
|                                                                                |
|ata0 master: v86 HD ATAPI-6 CD-Rom/DVD-Rom                                      |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
|                                                                                |
+================================================================================+
Test failed: Linux with Bochs BIOS

Expected text "/root%" after 90 seconds.
```

**Comment by MailYouLater** [comment]
Note: The failing "Linux with Bochs BIOS" test is why I was looking at this issue, but it's separate and should be addressed separately.

**Comment by copy** [comment]
This is fixed in current master.
