### ISSUE TITLE
Issue Loading State File

### ISSUE THREAD

**Issue by cemalgnlts** [copy/v86#878]
Hi,

I complete the boot process of the linux kernel with Node and save the state, then when I upload it to the web page, I get the following error:

```
libv86.js:27 Uncaught (in promise) TypeError: **Cannot read properties of null (reading '0')**
    at Virtio9p.set_state (libv86.js:27:68)
    at CPU.set_state (libv86.js:598:516)
    at CPU.restore_state (libv86.js:433:90)
    at v86.restore_state (libv86.js:72:57)
    at V86Starter.e (libv86.js:719:180)
```

State file  _(512 MB ram)_: [linux_state.bin.zst](https://app.circleci.com/pipelines/github/cemalgnlts/now-linux-build/148/workflows/91258551-aa74-45b4-b42e-2a1771dc9099/jobs/156/artifacts).
Node file for saving state: [index.js](https://github.com/cemalgnlts/now-linux-build/blob/master/now/index.js).
Build logs: [Boost Node.js and Create State File & Compress State File](https://app.circleci.com/pipelines/github/cemalgnlts/now-linux-build/148/workflows/91258551-aa74-45b4-b42e-2a1771dc9099/jobs/156/steps).

**Comment by cemalgnlts** [comment]
I guess it's because I didn't add the uart1 option while saving the state, I'll try again.

**Comment by cemalgnlts** [comment]
Yes, problem solved.

Thanks.
